# Generated by Django 6.0 on 2025-12-14 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_search_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, help_text='Descriptive text for meta-content tag for searches for the tag'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='difficulty',
            field=models.FloatField(help_text='Difficulty, 0=very easy, 10=very hard'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='The images associated with this activity.', to='activities.image'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='Minimum age for which the activity is suitable', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_age_with_help',
            field=models.IntegerField(blank=True, help_text='Minimum age for which the activity is suitable given help', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pdfs',
            field=models.ManyToManyField(blank=True, help_text='The PDFs associated with this activity.', to='activities.pdf'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this activity.', to='activities.tag'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(help_text='Descriptive text about the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='The title of this activity.', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date &amp; time at which the activity last had a (significant) update'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='urlname',
            field=models.SlugField(help_text='The unique name to use in URLs to identify this activity.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='The videos associated with this activity.', to='activities.video'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(upload_to='image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slideshow',
            field=models.CharField(choices=[('y', 'Include in slideshow'), ('n', "Don't include in slideshow")], max_length=1),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.FileField(upload_to='pdf/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='type',
            field=models.CharField(choices=[('i', 'Instruction sheet'), ('t', 'Template'), ('o', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Subtags of this tag.', to='activities.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Descriptive text for meta-content tag for searches for the tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='displaytext',
            field=models.CharField(blank=True, help_text='A longer piece of text describing the tag.  Optional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, help_text='An icon for this tag.', upload_to='tagicon/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon_selected',
            field=models.ImageField(blank=True, help_text='An icon to use when this tag is selected.', null=True, upload_to='tagicon/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True, help_text='Number to control the order', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='synonyms',
            field=models.ManyToManyField(blank=True, help_text='Synonyms of this tag.', to='activities.tagsynonym'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(help_text='The unique text identifying this tag', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('a', 'Display,search,browse'), ('s', 'Search,browse'), ('c', 'Navigation category'), ('b', 'Navigate with buttons')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tagsynonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagsynonym',
            name='text',
            field=models.CharField(help_text='The text for this synonym', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.TextField(blank=True, help_text='Identifier code for the video', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height of the video box', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('d', 'demonstration')], max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width of the video box', null=True),
        ),
    ]
